import os
from datetime import datetime
from pathlib import Path

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.amazon.aws.hooks.s3 import S3Hook


DATASETS_DIR = Path(os.getenv("DATASETS_DIR", Path(__file__).resolve().parents[2] / "datasets"))
INPUT_FILE = DATASETS_DIR / "sales_cleaned.csv"
OUTPUT_FILE = DATASETS_DIR / "sales_downloaded.csv"


def extract() -> str:
    """Read the cleaned CSV file and return as JSON."""
    df = pd.read_csv(INPUT_FILE)
    return df.to_json(orient="records")


def upload_to_s3(**context) -> str:
    """Upload the CSV file to S3/MinIO."""
    hook = S3Hook(aws_conn_id="minio_s3")
    
    # Upload file
    hook.load_file(
        filename=str(INPUT_FILE),
        key="sales/sales_cleaned.csv",
        bucket_name="airflow-data",
        replace=True,
    )
    
    return f"s3://airflow-data/sales/sales_cleaned.csv"


def list_s3_objects(**context) -> list:
    """List objects in the S3 bucket to verify upload."""
    hook = S3Hook(aws_conn_id="minio_s3")
    objects = hook.list_keys(bucket_name="airflow-data", prefix="sales/")
    return objects


def download_from_s3(**context) -> None:
    """Download the file back from S3 and verify."""
    hook = S3Hook(aws_conn_id="minio_s3")
    
    # Download file
    hook.download_file(
        key="sales/sales_cleaned.csv",
        bucket_name="airflow-data",
        local_path=str(OUTPUT_FILE),
        preserve_file_name=True,
        use_autogenerated_subdir=False,
    )
    
    # Verify download
    if OUTPUT_FILE.exists():
        df = pd.read_csv(OUTPUT_FILE)
        print(f"Downloaded {len(df)} rows from S3")
    else:
        raise FileNotFoundError(f"Failed to download file from S3")


# Import pandas inside the DAG to avoid serialization issues
import pandas as pd

with DAG(
    dag_id="s3_pipeline_dag",
    start_date=datetime(2024, 1, 1),
    schedule=None,
    catchup=False,
    tags=["learning", "s3", "minio", "cloud-storage"],
) as dag:
    extract_task = PythonOperator(task_id="extract", python_callable=extract)
    upload_task = PythonOperator(task_id="upload_to_s3", python_callable=upload_to_s3)
    list_task = PythonOperator(task_id="list_s3_objects", python_callable=list_s3_objects)
    download_task = PythonOperator(task_id="download_from_s3", python_callable=download_from_s3)
    
    extract_task >> upload_task >> list_task >> download_task